/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eYvaNejesYxSLtRjN5K9nx

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: eYvaNejesYxSLtRjN5K9nx/projectModule

const data = {
  base: `${"plasmic_tokens_eYvaNejesYxSLtRjN5K9nx"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
